name: AWS VM daily report
on:
  push:
    branches: [daily_vm_report]
  schedule:
    - cron: '0 0 * * *'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_KEY }}
  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
jobs:
  backport:
    runs-on: ubuntu-20.04
    name: AWS VM check
    steps:
    - uses: actions/checkout@v2
    - name: Install AWS CLI 2
      run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      shell: bash
    - name: AWS vm list
      run: |
           shell-script/useless-vm-check.sh
      shell: bash
           